(*first paragraph by Rebecca*)
At first, Jennifer couldn't decide which kind of tea she wanted. The chamomile, which used to be her favorite for lazy evenings at home, now reminded her too much of Carl, who once said, in happier times, that he liked chamomile. But she felt she must now, at all costs, keep her mind off Carl. His possessiveness was suffocating, and if she thought about him too much her asthma started acting up again. So chamomile was out of the question.

(*second paragraph by Gary*)
Meanwhile, Advance Sergeant Carl Harris, leader of the attack squadron now in orbit over Skylon 4, had more important things to think about than the neuroses of an air-headed asthmatic bimbo named Jennifer with whom he had spent one sweaty night over a year ago. 'A.S. Harris to Geostation 17,' he said into his transgalactic communicator. 'Polar orbit established. No sign of resistance so far...' But before he could sign off a bluish particle beam flashed out of nowhere and blasted a hole through his ship's cargo bay. The jolt from the direct hit sent him flying out of his seat and across the cockpit.

(*Rebecca*)
He bumped his head and died almost immediately, but not before he felt one last pang of regret for psychically brutalizing the o ne wom an who had ever had feelings for him. Soon afterwards, Earth stopped its pointless hostilities towards the peaceful farmers of Skylon 4. 'Congress Passes Law Permanently Abolishing War and Space Travel,' Jennifer read in her newspaper one morning. The news simultaneously excited her and bored her. She stared out the window, dreaming of her youth, when the days had passed unhurriedly and carefree, with no newspaper to read, no television to distract her from her sense of innocent wonder at all the beautiful things around her. 'Why must one lose one's innocence to become a woman?' she pondered wistfully.

(*Gary*)
Little did she know, but she had less than 10 seconds to live. Thousands of miles above the city, the Anudrian mother ship launched the first of its lithium fusion missiles. The dimwitted wimpy peaceniks who p ushed the Unilateral Aerospace Disarmament Treaty through the congress had left Earth a defenseless target for the hostile alien empires who were determined to destroy the human race. Within two hours after the passage of the treaty, the Anudrian ships were on course for Earth, carrying enough firepower to pulverize the entire planet. With no one to stop them, they swiftly initiated their diabolical plan. The lithium fusion missile entered the atmosphere unimpeded. The President, in his top-secret mobile submarine headquarters on the ocean floor off the coast of Guam, felt the inconceivably massive explosion, which vaporized poor, stupid Jennifer.